### ISSUE TITLE
Continuous Deployment for Bounty Hunters

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ts-template#1]
Please create a GitHub Action that will automatically create a new Cloudflare Pages instance automatically (we eventually will need a dedicated Ubiquity Cloudflare account to deploy to!) and then build/host pull requests made by public forks of bounty hunters.

We need to create (or fork) a custom GitHub Action to use Cloudflare Wrangler to automatically deploy a preview when bounty hunters open up a pull request in order to make the review process more efficient.

> Every time you open a new pull request on your GitHub repository, Cloudflare Pages will create a unique preview URL, which will stay updated as you continue to push new commits to the branch. This is only true when pull requests originate from the repository itself.

[Source](https://developers.cloudflare.com/pages/platform/preview-deployments/).

**Comment by cuddle-dev** [comment]
https://github.com/0xcodercrane/ts-template/actions/runs/4864759293/jobs/8674195873?pr=1

![image](https://user-images.githubusercontent.com/108444211/235760369-9688b4fc-af3a-4580-92e7-466fefb88b9e.png)

@pavlovcik  ^^

**Comment by 0x4007** [comment]
> https://github.com/0xcodercrane/ts-template/actions/runs/4864759293/jobs/8674195873?pr=1
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/108444211/235760369-9688b4fc-af3a-4580-92e7-466fefb88b9e.png)
> 
> 
> 
> @pavlovcik  ^^

Thank you for posting proof. There doesn't appear to be a linked pull request. 

Does the tutorial comment bug out when I edit my first comment on the repository issues?

Looks like I found a bug lol

**Comment by 0x4007** [comment]
I got it [to work](https://github.com/ubiquity/ubiquibot-sandbox/actions/runs/4868070182) but: 
1. Would you mind only naming it the repository name (don't include the organization name in the Cloudflare Page project name) this follows the Cloudflare app naming behavior.
2. You may need to "pause deployments" ? It could be done in the following CI step, after successful deployment perhaps?
3. What happens on a name collision? I think it makes sense to throw an error, but I hope with a manual rename, that this CI/CD will be functional. I hope I articulated this scenario clearly enough.

<img width="591" alt="image" src="https://user-images.githubusercontent.com/4975670/235831544-514556c3-9ff5-455c-8ee3-691f7018ccbd.png">

**Comment by cuddle-dev** [comment]
1. Would you mind only naming it the repository name --- yes
2. I am not sure why we need to pause deployments after the successful deployment
3. Each project is being distinguished by the project name. We can even put the project name manually in ci/cd. just needs a minor change on workflow file

@pavlovcik

**Comment by 0x4007** [comment]
> 2 

My assumption is that It could cause redundant deployments (like 2 or 3 at the same time off of the same commit.) No harm in testing leaving it on then.

**Comment by 0x4007** [comment]
This looks like it might be done?

**Comment by cuddle-dev** [comment]
> This looks like it might be done?

Yes I think its done if you don't have any coments but if theres anything for improvements, need to jump on it again

**Comment by 0x4007** [comment]
Why didn't you associate your pull request to this issue?

**Comment by cuddle-dev** [comment]
mistakenly I pushed the main changes to the `develompent` branch direclty and here's a refactor PR for renaming.
https://github.com/ubiquity/ts-template/pull/4

**Comment by 0x4007** [comment]
Is this finished?

**Comment by cuddle-dev** [comment]
> Is this finished?

I think yeah. we were already using it on [ubiquity/pay.ubq.fi](https://github.com/ubiquity/pay.ubq.fi/blob/main/.github/workflows/continuous-deploy.yml) right?

**Comment by 0x4007** [comment]
If you want to take the bounty reward then you should associate your proof of work with this issue, self assign, and then close. 

In the future you should be mindful of associating a pull request so that we can standardize the work audit process to scale.

**Comment by cuddle-dev** [comment]
**This has been done by the following commits.**

1. https://github.com/ubiquity/ts-template/commit/5ce8aefcd4e839d55169156229ecce75d25dd7b0
2. https://github.com/ubiquity/ts-template/commit/d1e8b0b52130f6cc206675b7e2b8b616da2fda81
3. https://github.com/ubiquity/ts-template/commit/af605734b9a66fa4b1d5b5887704e2940de43cf6
4. https://github.com/ubiquity/ts-template/commit/d2cb9f89841650c76596a03d0eab4a3026244247
5. https://github.com/ubiquity/ts-template/commit/3b84211723362d01b848eab143727e39af411202
6. https://github.com/ubiquity/ts-template/commit/e80cbfe8d3f7bf2bbb8043f09e4aedc615b657b4

**The POW is** 

1. Continuous deployment script is done in [ubiquity/ts-template](https://github.com/ubiquity/ts-template/blob/development/.github/workflows/cloudflare-deploy.yml)
2. The same action file is being used in the [continuous-deploy.yml](https://github.com/ubiquity/pay.ubq.fi/blob/main/.github/workflows/continuous-deploy.yml) and it deployed the sites to the [cloudflare page](https://6b515fb5.ubiquity-bounty-claims.pages.dev/) successfully.

**Comment by cuddle-dev** [comment]
Adding the [PR](https://github.com/ubiquity/ubiquity-dollar/pull/677) in ubiquity/ubiquity-dollar repo for the Proof of Work
