### ISSUE TITLE
Add testing into repository template

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity/ts-template#15]
I think it would be nice to have a testing set up by default on every project. Since we are currently adding unit testing to all the project, we end up copying the same files around.

What would be needed:
- an Action file to trigger the testing on push
- to have Jest in the dev dependencies and the corresponding script
- to have a default Jest config with coverage
- a basic test file setup

You can refer to project like https://github.com/ubiquity/devpool-directory to see how it was done.

**Comment by molecula451** [comment]
cc @pavlovcik for permit generation
