### ISSUE TITLE
Test UI for Errors

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ts-template#18]
Set up Cypress to automatically throw an error in CI if `static/index.html` throws any errors in the console on page load. 

This should catch most issues I think because our apps are so simple. 

No need to click buttons or anything yet.

**Comment by gentlementlegen** [comment]
Depends on https://github.com/ubiquity/ts-template/issues/15 to be merged first to avoid clashes between both test libraries (Cypress / Jest).

**Comment by 0x4007** [comment]
Very cool to see this feature in action, thanks @FernandVEYRIER !

https://www.github.com/ubiquity/work.ubq.fi/pull/23#issuecomment-1979854728
