### ISSUE TITLE
Empty String `""` Code Review Warning Annotation

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ts-template#31]
Annotate them with warnings in code review to more closely scrutinize the logic that interacts with the variable. 

### Rationale
I see a lot of abuse for empty strings. It makes code logic sloppy and more error prone. But since there are some legitimate uses for empty strings, we will just set a warning instead of error?

###### https://github.com/ubiquity/audit.ubq.fi/blob/08fba85a9a592ca2bda5eaeaa2ff3b9fdd4632be/static/scripts/audit-report/audit.ts#L26C1-L27C21

- Should be unset (which implies `undefined`) instead of passing an empty string as a credential or URL. Then the code should check if the value is truthy before expecting authentication.
```typescript
let REPOSITORY_URL;
let GITHUB_PAT;
```

###### https://github.com/ubiquity/ubiquibot-kernel/blame/c553d5a7866c1ef76d4f589d8095c8bb751cbd49/src/github/types/config.ts#L29

- Should be `value.ref ?? "@" + value.ref` as I'm assuming the developer never expected the `""` value to be returned there. 

###### https://github.com/ubiquity/pay.ubq.fi/pull/189/files#r1518549017

- This shouldn't have been here at all. It's not a valid RPC endpoint.

---

**Comment by Keyrxng** [comment]
/stop if it is still an open task I will pick it back up. Feel free to ref my PR if anyone wants to take this

**Comment by 0x4007** [comment]
> ```diff
> ! Failed to run comment evaluation. TypeError: Cannot read properties of undefined (reading 'wordValue')
> ```
> 

@gentlementlegen  can you fix today and leverage Whilefoo environment config switcher

**Comment by gentlementlegen** [comment]
@0x4007 I should have tested this, but it will always crash if a user opens a pull request because it uses variables from secrets that are not accessible, I will fix that.
