### ISSUE TITLE
Three Letter Linter

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ts-template#39]
Make a custom lint rule enforcing this. Check previous conversation 

> Our coding style guide should have this written as `Erc20Permit`

> It is an implicit rule according to the contributing.md in the Ubiquity Dollar repo

_Originally posted by @0x4007 in https://github.com/ubiquity/pay.ubq.fi/pull/224#discussion_r1569165738_

**Comment by gentlementlegen** [comment]
I think that `PascalCase` rule would be a better name for this issue 😄

**Comment by gitcoindev** [comment]
> I think that `PascalCase` rule would be a better name for this issue 😄

or UpperCamelCase. But Three letter linter is a catchy name as it made me to click on this issue 😄

**Comment by jordan-ae** [comment]
@0x4007 should the linter ensure every variable respects PascalCase or just the Erc20Permit and Erc721 should follow this rule?
