### ISSUE TITLE
Configure lint-staged hook correctly.

### ISSUE THREAD

**Issue by jordan-ae** [ubiquity/ts-template#41]
We have lint-staged for this purpose but perhaps it's not configured correctly.

_Originally posted by @0x4007 in https://github.com/ubiquity/ts-template/issues/40#issuecomment-2071289984_

**Comment by gentlementlegen** [comment]
@jordan-ae please provide a more in-depth description, and add a time estimate to it, thanks

**Comment by rndquu** [comment]
> @jordan-ae please provide a more in-depth description, and add a time estimate to it, thanks

As far as I understand this issue implies fixing running husky hooks (`lint-staged` in particular) on github commit. 

So we need to:
1. Make sure husky is setup on `yarn install` ([here](https://github.com/ubiquity/ts-template/blob/c99c565e0873bf6f2b3d45de7e2ddca977de9da6/package.json#L20) it should be `postinstall`)
2. Make sure ts files are linted on commit

**Comment by jordan-ae** [comment]
@gentlementlegen @rndquu this ticket might not need to exist. From my recent commits the lint-stage hook has been working correctly. We should close this as not planned.
