### ISSUE TITLE
CI: refactor knip to run on `pull_request` event

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ts-template#42]
What should be done:
- refactor https://github.com/ubiquity/ts-template/blob/development/.github/workflows/knip.yml to run in 2 steps ([one](https://github.com/ubiquity/rpc-handler/blob/development/.github/workflows/knip.yml), [two](https://github.com/ubiquity/rpc-handler/blob/development/.github/workflows/knip-reporter.yml)) because `pull_request_target` may leak org secrets

Related [comment](https://github.com/ubiquity/rpc-handler/pull/13#issuecomment-2123006059)

@gitcoindev FYI

**Comment by gentlementlegen** [comment]
Very old related task to this:
https://github.com/ubiquity/cloudflare-deploy-action/issues/6
