### ISSUE TITLE
Disable Coverage Report Comment 

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ts-template#50]
I don't like the notifications on every commit. Please do not post these as a comment. 

https://github.com/ubiquity/webauthn-evm-signing-key/commit/59301faa885d775c50de3e80d200b947717a2b8b#commitcomment-143320074

https://github.com/ubiquity/ts-template/blob/development/.github/workflows/jest-testing.yml#L25-L31

**Comment by 0x4007** [comment]
I also forgot to ask, but can you remove this feature from every repository that it's apart of? I still get notifications from the other repositories. 

User activity watcher is the latest one. You can probably use GitHub repository search and double check all the repository that were created within the last three weeks

**Comment by gentlementlegen** [comment]
Impacted repos:
- [ ] https://github.com/ubiquity/ts-template: https://github.com/ubiquity/ts-template/pull/51
- [ ] https://github.com/ubiquibot/plugin-template: https://github.com/ubiquibot/plugin-template/pull/9
- [ ] https://github.com/ubiquibot/user-activity-watcher: https://github.com/ubiquibot/user-activity-watcher/pull/7
- [ ] https://github.com/ubiquibot/command-query-user: https://github.com/ubiquibot/command-query-user/pull/7
- [ ] https://github.com/ubiquibot/conversation-rewards: https://github.com/ubiquibot/conversation-rewards/pull/44
