### ISSUE TITLE
Default Env Vars

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ts-template#58]
Maintaining our projects is incredibly burdensome to set up for the first time (and we have a lot of repos)

We need to start providing default secrets bundled in to get started quickly. This should be for everything. This implies that we need to make essentially disposable assets for anything GitHub related (user accounts, orgs, apps)

For other paid services, like OPEN AI, we can let contributors worry about it themselves given that they have extensive documentation.

**Comment by YanVictorSN** [comment]
Hi @0x4007 For this task we need to create and set Accounts/API keys related to all repositories in Ubiquity? Is that it?
