### ISSUE TITLE
Create a reusable web deploy workflow

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ts-template#6]
Right now for each repository which requires a web deploy we use separate github workflows ([example 1](https://github.com/ubiquity/ubiquity-dollar/blob/development/.github/workflows/continuous-deploy.yml) and [example 2](https://github.com/ubiquity/pay.ubq.fi/blob/main/.github/workflows/continuous-deploy.yml))

Github has a [feature of reusing workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow) across all repositories in a single organisation

What should be done:
1. Create a reusable web deploy workflow (which will deploy to cloudflare pages in our case)
2. Remove old deployment workflows and apply the new reusable workflow to these repos:
- https://github.com/ubiquity/ubiquity-dollar
- https://github.com/ubiquity/pay.ubq.fi
- https://github.com/ubiquity/ubq.fi
3. Add feature of supporting custom domains like `2aa376b3.pay-ubq-fi.ubiquitydao.dev`

So in the end we should get a reusable workflow which:
- can be easily integrated into any organisation's repo
- produces the following [deploy result comment](https://github.com/ubiquity/ubiquity-dollar/pull/700#issuecomment-1602409352) by the [ubiquibot](https://github.com/ubiquity/ubiquity-dollar/blob/development/.github/workflows/continuous-deploy.yml#L80)

---

Improvement of https://github.com/ubiquity/ts-template/issues/1

**Comment by 0x4007** [comment]
It isn't clear to me how this will solve the original proposed problem. Sure we can have the core logic in a shared workflow file but each repository still must call the shared workflow with a new workflow file. Mind as well just fork the core logic and add to every repository anyways. 

My proposal was to have our bot automatically have it on for every repo without any custom setup/configuration required.

**Comment by rndquu** [comment]
> It isn't clear to me how this will solve the original proposed problem. Sure we can have the core logic in a shared workflow file but each repository still must call the shared workflow with a new workflow file. Mind as well just fork the core logic and add to every repository anyways.
> 
> My proposal was to have our bot automatically have it on for every repo without any custom setup/configuration required.

The original problem is described [here](https://github.com/ubiquity/pay.ubq.fi/pull/76#pullrequestreview-1494617742)

As far as I understand the issue is that the web app deploy hasn't been performed in order to check how the feature works

So this issue describes a solution to create a universal workflow for web app deploys so that we wouldn't check yml config files every time there is smth wrong with the deploy

We shouldn't add the web deploy feature to the bot because:
1. Partners might not need web app deploys (in case they have a backend or solidity or any other repo). So this feature is really applicable only to our project.
2. This is not really the bot's task to manage deployments. Github already does a great job on this. The bot should be responsible for it's main feature: managing bounties.

**Comment by 0x4007** [comment]
> It isn't clear to me how this will solve the original proposed problem.

https://t.me/c/1588400061/1/3729

> I thought about this because the alternative is that we must be sure to manually add the CI/CD YML file to every repository OR it can “just work” if the bot is added to a repo. 

> web app deploy hasn't been performed

I'm unsure if I am understanding but 0xcodercrane already included the logic to automatically check if the inital deployment was created, and if not, to create a new project on Cloudflare and do the deployment. This logic is inside of the [continuous-deploy.yml:54](https://github.com/ubiquity/ubiquity-dollar/blob/ad8e02cb904edef7861431892170ba897d39c2c8/.github/workflows/continuous-deploy.yml#L54)

> So this issue describes a solution to create a universal workflow for web app deploys so that we wouldn't check yml config files every time there is smth wrong with the deploy

So this forces us to use the same core logic, meaning that either it should always work across all repositories or none at all. Okay that makes sense.

> We shouldn't add the web deploy feature

Agreed with your points

**Comment by whilefoo** [comment]
The comment action (thollander/actions-comment-pull-request) does not support commenting on other repos. Since this will be also used by partners, maybe it's better to leave the option of commenting to the caller workflow?

EDIT: I have found an alternative action that can do that

**Comment by whilefoo** [comment]
Will the reusable workflow be placed in this repo? Because this repo is a template, it will get copied over to every repo.

**Comment by rndquu** [comment]
> Will the reusable workflow be placed in this repo? Because this repo is a template, it will get copied over to every repo.

I don't think so because https://github.com/ubiquity/ts-template was initially created both for frontend and backend while cloudflare pages (as far as I understand) supports only static html

**Comment by 0x4007** [comment]
> it will get copied over to every repo

It does not get automatically copied over to every repo. I've made several changes to this repo and had to manually sync them on other repos. 

@rndquu let's focus on the front-and-back-end support and if necessary we can make other templates for other types of projects.

**Comment by whilefoo** [comment]
> It does not get automatically copied over to every repo.

Yes, I meant to say when somebody uses this template to create a new repo it will get copied over. Which repo should I place the reusable workflow to?

**Comment by 0x4007** [comment]
> Which repo should I place the reusable workflow to

@rndquu should we make a new repository for this reusable workflow?

**Comment by rndquu** [comment]
> > It does not get automatically copied over to every repo.
> 
> Yes, I meant to say when somebody uses this template to create a new repo it will get copied over. Which repo should I place the reusable workflow to?

I would put it in https://github.com/ubiquity/.github

**Comment by whilefoo** [comment]
> 2\. Remove old deployment workflows and apply the new reusable workflow to these repos:
> 
> * https://github.com/ubiquity/ubiquity-dollar
> * https://github.com/ubiquity/pay.ubq.fi
> * https://github.com/ubiquity/ubq.fi

I still have to do this part of the task

**Comment by 0x4007** [comment]
> ### [**[ CLAIM 200 DAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHg2QjE3NTQ3NEU4OTA5NEM0NERhOThiOTU0RWVkZUFDNDk1MjcxZDBGIiwiYW1vdW50IjoiMjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiMTExMjAyNzA4MjUyNTQxNzMyMTUyNTEyMzYwOTM0MjExNTUyNDM5OTYxNzM5NDQ5NTIwNzY5MTM4MTg0MDUzMDg2NjY1MDY3MjIwOTUxIiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHhBMEIxMUY0NzRkOEVDRTEyMDVkMzhjNjZkNUYyYkU4OTE3Njc1ZDYwIiwicmVxdWVzdGVkQW1vdW50IjoiMjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHg5MDFkY2EyNWM0MTQ4NmFlOTE1MzJiMWE1YzhiNjc0NGNjMzhkMTY5ZWMyNTFmZWQ4NzE0ZGY3MTJkYWJhOWY4MDY2NjYzNGFiNDhhNDIyZGQyZmQ1ZjgzYzVhODhmYzM0ZTAyYjRiMDAyMmFlZWMxMDYxZmQyZTFhOGUyNzhlYzFiIn0=&network=1)
> `0xA0B11F4...17675d60`
> 
> ###### If you enjoy the DevPool experience, please follow [Ubiquity on GitHub](https://github.com/ubiquity) and star [this repo](https://github.com/ubiquity/devpool-directory) to show your support. It helps a lot!

@0xcodercrane @wannacfuture why is this paid out in DAI?

**Comment by cuddle-dev** [comment]
> > ### [**[ CLAIM 200 DAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHg2QjE3NTQ3NEU4OTA5NEM0NERhOThiOTU0RWVkZUFDNDk1MjcxZDBGIiwiYW1vdW50IjoiMjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiMTExMjAyNzA4MjUyNTQxNzMyMTUyNTEyMzYwOTM0MjExNTUyNDM5OTYxNzM5NDQ5NTIwNzY5MTM4MTg0MDUzMDg2NjY1MDY3MjIwOTUxIiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHhBMEIxMUY0NzRkOEVDRTEyMDVkMzhjNjZkNUYyYkU4OTE3Njc1ZDYwIiwicmVxdWVzdGVkQW1vdW50IjoiMjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHg5MDFkY2EyNWM0MTQ4NmFlOTE1MzJiMWE1YzhiNjc0NGNjMzhkMTY5ZWMyNTFmZWQ4NzE0ZGY3MTJkYWJhOWY4MDY2NjYzNGFiNDhhNDIyZGQyZmQ1ZjgzYzVhODhmYzM0ZTAyYjRiMDAyMmFlZWMxMDYxZmQyZTFhOGUyNzhlYzFiIn0=&network=1)
> > `0xA0B11F4...17675d60`
> > ###### If you enjoy the DevPool experience, please follow [Ubiquity on GitHub](https://github.com/ubiquity) and star [this repo](https://github.com/ubiquity/devpool-directory) to show your support. It helps a lot!
> 
> @0xcodercrane @wannacfuture why is this paid out in DAI?

Looks like ts-template has no config so it seems defaults to DAI in ETH. @rndquu  for confirmation

**Comment by rndquu** [comment]
> > > ### [**[ CLAIM 200 DAI ]** ](https://pay.ubq.fi?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHg2QjE3NTQ3NEU4OTA5NEM0NERhOThiOTU0RWVkZUFDNDk1MjcxZDBGIiwiYW1vdW50IjoiMjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiMTExMjAyNzA4MjUyNTQxNzMyMTUyNTEyMzYwOTM0MjExNTUyNDM5OTYxNzM5NDQ5NTIwNzY5MTM4MTg0MDUzMDg2NjY1MDY3MjIwOTUxIiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHhBMEIxMUY0NzRkOEVDRTEyMDVkMzhjNjZkNUYyYkU4OTE3Njc1ZDYwIiwicmVxdWVzdGVkQW1vdW50IjoiMjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHg5MDFkY2EyNWM0MTQ4NmFlOTE1MzJiMWE1YzhiNjc0NGNjMzhkMTY5ZWMyNTFmZWQ4NzE0ZGY3MTJkYWJhOWY4MDY2NjYzNGFiNDhhNDIyZGQyZmQ1ZjgzYzVhODhmYzM0ZTAyYjRiMDAyMmFlZWMxMDYxZmQyZTFhOGUyNzhlYzFiIn0=&network=1)
> > > `0xA0B11F4...17675d60`
> > > ###### If you enjoy the DevPool experience, please follow [Ubiquity on GitHub](https://github.com/ubiquity) and star [this repo](https://github.com/ubiquity/devpool-directory) to show your support. It helps a lot!
> > 
> > 
> > @0xcodercrane @wannacfuture why is this paid out in DAI?
> 
> Looks like ts-template has no config so it seems defaults to DAI in ETH. @rndquu for confirmation

fixed https://github.com/ubiquity/ubiquibot-config/commit/b86562d3be15fcbebe3dd46e3b11fd7bea76f48c

**Comment by whilefoo** [comment]
Can you invalidate this permit and generate permit for gnosis chain?

**Comment by 0x4007** [comment]
Gas is extremely high so I initiated the [invalidation transaction](https://etherscan.io/tx/0x8463f8851db776d87aca7799c187136afdcbe9760bd3b1b4ae6a88128bd36b3c). Whenever it is completed I can generate the new payment permit on Gnosis Chain.

**Comment by 0x4007** [comment]
> Can you invalidate this permit and generate permit for gnosis chain?

Done @whilefoo

**Comment by rndquu** [comment]
@whilefoo Would you mind setting the reusable deploy for the https://github.com/ubiquity/ubiquity-dollar repo ?

**Comment by whilefoo** [comment]
> @whilefoo Would you mind setting the reusable deploy for the https://github.com/ubiquity/ubiquity-dollar repo ?

It's already done

**Comment by rndquu** [comment]
> > @whilefoo Would you mind setting the reusable deploy for the https://github.com/ubiquity/ubiquity-dollar repo ?
> 
> It's already done

Oh, thank you, I might've missed it
