### ISSUE TITLE
Disable the Non-null Assertion Operator with Linting

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ts-template#7]
There's a lot of abuse in our codebases with contributors using "!" 

Example: 
```typescript
let element: HTMLElement | null = document.getElementById('test');

// This would throw a TypeScript error without the "!" because element could be null
let value: string = element!.innerText;
```

Enforce that this can not pass our linters.

**Comment by b4s36t4** [comment]
@pavlovcik Rule should be enabled in this repo only right? https://github.com/ubiquity/ubiquibot

**Comment by 0x4007** [comment]
In this template. We have to manually fix every issue based on the linter settings set up here.

**Comment by b4s36t4** [comment]
https://github.com/ubiquity/ubiquity-dollar/blob/82077e295e996c7b8f774ec3ded73ca5637ca2af/utils/kebabalize-filenames.ts#L36

https://github.com/ubiquity/pay.ubq.fi/blob/bca42a52e57cf2bc7aa4390f909f891005e4ba23/static/scripts/pay.ts#L58

Found only these two place where non-null assertion is being used. Do you know any places or specific repo to have the same? 

If not ready to pickup this.

**Comment by 0x4007** [comment]
I was cleaning a handful of them yesterday in pay.ubq.fi repository so I'm not sure. 

Either way, they shouldn't be used in almost every example that I've come across. 

Yes we should disable in our linter.

**Comment by baibhavKumar1** [comment]
@pavlovcik , we can disable this in the linter, but what's alternate for "!" in codebase in your opinion? Should we change it with "?" mark?

**Comment by 0x4007** [comment]
> @pavlovcik , we can disable this in the linter, but what's alternate for "!" in codebase in your opinion? Should we change it with "?" mark? 

Correct typings. Just never use `any`. 

It's straightforward if you know typings. Just more work with certain complex objects.

**Comment by 3scava1i3r** [comment]
> > @pavlovcik , we can disable this in the linter, but what's alternate for "!" in codebase in your opinion? Should we change it with "?" mark?
> 
> Correct typings. Just never use `any`.
> 
> It's straightforward if you know typings. Just more work with certain complex objects.

In this template or every repo by ubiquity?

**Comment by Wholesomebruh** [comment]
> > > @pavlovcik , we can disable this in the linter, but what's alternate for "!" in codebase in your opinion? Should we change it with "?" mark?
> > 
> > 
> > Correct typings. Just never use `any`.
> > It's straightforward if you know typings. Just more work with certain complex objects.
> 
> In this template or every repo by ubiquity?

It should be implemented in every repo.

**Comment by 0x4007** [comment]
> > > @pavlovcik , we can disable this in the linter, but what's alternate for "!" in codebase in your opinion? Should we change it with "?" mark?
> 
> > 
> 
> > Correct typings. Just never use `any`.
> 
> > 
> 
> > It's straightforward if you know typings. Just more work with certain complex objects.
> 
> 
> 
> In this template or every repo by ubiquity?

Both!
