### ISSUE TITLE
Fix secrets usage

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity/ts-template#75]
@0x4007 I should have tested this, but it will always crash if a user opens a pull request because it uses variables from secrets that are not accessible, I will fix that.

_Originally posted by @gentlementlegen in https://github.com/ubiquity/ts-template/issues/31#issuecomment-2464146839_
            

Many variables of the script reference secrets, which do not exist on PRs for security reasons. They have to be replaced or default to something for graceful fallback.

**Comment by 0x4007** [comment]
> ```diff
> ! No price label is set to calculate the duration
> ```
> 

This error doesn't make sense it should be removed.
