### ISSUE TITLE
Plugin installer review changes

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity/ts-template#79]
- [Source](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/pull/13#discussion_r1835570450): Would be better to run this on pull request events.
- [Source](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/pull/13#discussion_r1835570183): Ideally I think we should use the latest version of eslint that provides better feedback: https://github.com/ubiquity-os/plugin-template/blob/development/eslint.config.mjs

**Comment by zugdev** [comment]
I've already handled transitioning into eslint v9, so this one is about changing the cypress flow to run on PR? This spec was kinda weird to read.
