### ISSUE TITLE
`Empty String Check` workflow: exclude files

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ts-template#82]
Check [this](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/actions/runs/11914418242/job/33202289177?pr=13) failing `Empty String Check` workflow. It fails because there're empty strings in the following places:
- [one](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/blob/406cac7a7f77be8c8d572d0f39b378722ae867fb/static/scripts/render-manifest.ts#L295)
- [two](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/blob/406cac7a7f77be8c8d572d0f39b378722ae867fb/static/scripts/render-manifest.ts#L440)
- [three](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/blob/406cac7a7f77be8c8d572d0f39b378722ae867fb/static/utils/ele-helpers.ts#L88)

So there are legit cases when empty strings can be used. 

What should be done:
- add a feature of excluding some files from empty strings check in the [no-empty-strings.yml](https://github.com/ubiquity/ts-template/blob/7b94011f7e080380dd5517db6a0b80ec6d5ae965/.github/workflows/no-empty-strings.yml) workflow

**Comment by Keyrxng** [comment]
The run is failing due to permission reasons @rndquu, this can be closed as not planned probs.

> POST /repos/ubiquity-os/ubiquity-os-plugin-installer/check-runs - 403 with id 1B40:4890C:25FDE3:2654FA:673C973B in 159ms
Error: An error occurred: Resource not accessible by integration - https://docs.github.com/rest/checks/runs#create-a-check-run

**Comment by rndquu** [comment]
> The run is failing due to permission reasons @rndquu, this can be closed as not planned probs.
> 
> > POST /repos/ubiquity-os/ubiquity-os-plugin-installer/check-runs - 403 with id 1B40:4890C:25FDE3:2654FA:673C973B in 159ms
> > Error: An error occurred: Resource not accessible by integration - https://docs.github.com/rest/checks/runs#create-a-check-run

There're still empty string warnings so the CI would fail anyway

**Comment by Keyrxng** [comment]
https://github.com/ubiquity/ts-template/blob/7b94011f7e080380dd5517db6a0b80ec6d5ae965/.github/empty-string-checker.ts#L55
 
You are right, my mistake, the original vision for it was that it would only present a diff warning but not crash CI so it would always succeed essentially but the diff would have it's comments

**Comment by obeys** [comment]
trying to push changes but running into some errors with ESint

```
yarn run v1.22.22
$ /workspaces/ts-template/node_modules/.bin/lint-staged
✔ Preparing lint-staged...
⚠ Running tasks for staged files...
  ❯ package.json — 2 files
    ❯ *.ts — 1 file
      ✔ yarn prettier --write
      ✖ eslint --fix [FAILED]
    ↓ src/**.{ts,json} — no files
↓ Skipped because of errors from tasks.
✔ Reverting to original state because of errors...
✔ Cleaning up temporary files...

✖ eslint --fix:

Oops! Something went wrong! :(

ESLint: 8.56.0

Error: ESLint configuration in .eslintrc » plugin:sonarjs/recommended is invalid:
        - Unexpected top-level property "name".

Referenced from: /workspaces/ts-template/.eslintrc
    at ConfigValidator.validateConfigSchema (/workspaces/ts-template/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2177:19)
    at ConfigArrayFactory._normalizeConfigData (/workspaces/ts-template/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3019:19)
    at ConfigArrayFactory._loadExtendedPluginConfig (/workspaces/ts-template/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3239:25)
    at ConfigArrayFactory._loadExtends (/workspaces/ts-template/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3154:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/workspaces/ts-template/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/workspaces/ts-template/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3040:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/workspaces/ts-template/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2886:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/workspaces/ts-template/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3871:46)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
husky - pre-commit script failed (code 1)
```

**Comment by rndquu** [comment]
> trying to push changes but running into some errors with ESint
> 
> ```
> yarn run v1.22.22
> $ /workspaces/ts-template/node_modules/.bin/lint-staged
> ✔ Preparing lint-staged...
> ⚠ Running tasks for staged files...
>   ❯ package.json — 2 files
>     ❯ *.ts — 1 file
>       ✔ yarn prettier --write
>       ✖ eslint --fix [FAILED]
>     ↓ src/**.{ts,json} — no files
> ↓ Skipped because of errors from tasks.
> ✔ Reverting to original state because of errors...
> ✔ Cleaning up temporary files...
> 
> ✖ eslint --fix:
> 
> Oops! Something went wrong! :(
> 
> ESLint: 8.56.0
> 
> Error: ESLint configuration in .eslintrc » plugin:sonarjs/recommended is invalid:
>         - Unexpected top-level property "name".
> 
> Referenced from: /workspaces/ts-template/.eslintrc
>     at ConfigValidator.validateConfigSchema (/workspaces/ts-template/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2177:19)
>     at ConfigArrayFactory._normalizeConfigData (/workspaces/ts-template/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3019:19)
>     at ConfigArrayFactory._loadExtendedPluginConfig (/workspaces/ts-template/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3239:25)
>     at ConfigArrayFactory._loadExtends (/workspaces/ts-template/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3154:29)
>     at ConfigArrayFactory._normalizeObjectConfigDataBody (/workspaces/ts-template/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3095:25)
>     at _normalizeObjectConfigDataBody.next (<anonymous>)
>     at ConfigArrayFactory._normalizeObjectConfigData (/workspaces/ts-template/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3040:20)
>     at _normalizeObjectConfigData.next (<anonymous>)
>     at ConfigArrayFactory.loadInDirectory (/workspaces/ts-template/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2886:28)
>     at CascadingConfigArrayFactory._loadConfigInAncestors (/workspaces/ts-template/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3871:46)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> husky - pre-commit script failed (code 1)
> ```

Should be fine when https://github.com/ubiquity/ts-template/pull/86 is merged
