### ISSUE TITLE
Use `eslint` v9

### ISSUE THREAD

**Issue by rndquu** [ubiquity/ts-template#87]
RIght now we're [using](https://github.com/ubiquity/ts-template/blob/7b94011f7e080380dd5517db6a0b80ec6d5ae965/package.json#L49) `eslint` v8 while the latest is v9.

What should be done:
1. Update `package.json` to use `eslint` v9
2. Update [.eslintrc](https://github.com/ubiquity/ts-template/blob/7b94011f7e080380dd5517db6a0b80ec6d5ae965/.eslintrc) accroding to the [breaking changes](https://eslint.org/docs/latest/use/migrate-to-9.0.0)
3. Use `plugin:sonarjs/recommended` [here](https://github.com/ubiquity/ts-template/blob/7b94011f7e080380dd5517db6a0b80ec6d5ae965/.eslintrc#L8C79-L8C105) 
4. Make sure `yarn lint-staged` works as expected

**Comment by zugdev** [comment]
Tho v9.15 is available, I will be using v9.14 because of recent compatibility issues with sonarjs: 

https://community.sonarsource.com/t/eslint-plugin-sonarjs-doesn-t-work-with-eslint-9-15-0/130771
